menu:
  Home: /
  Archives: /archives
  GitHub: https://github.com/inetfuture

widgets:
- search
- category
- tag
- recent_posts

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: UA-39930568-1
rss: